services:
    clutchengineering.posthog.listener:
        class: clutchengineering\posthog\event\listener
        arguments:
            - '@config'
            - '@language'
            - '@template'
            - '@user'
        tags:
            - { name: event.listener }
