services:
    phpbb.googleanalytics.listener:
        class: phpbb\googleanalytics\event\listener
        arguments:
            - '@config'
            - '@language'
            - '@template'
            - '@user'
        tags:
            - { name: event.listener }
